version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
                command: |
                   npm install --save-dev mocha
                   echo 'export PATH=./node_modules/.bin:$PATH' >> $BASH_ENV
                   npm test
          
workflows:
  build-and-test:
    jobs:
      - build-and-test
